#
# Copyright . All Rights Reserved.
#
version: '2'

#networks:
#  fabric_service:
#    external: true

services:
  nginx:
    network_mode: host
    container_name: nginx.$ORG.$DOMAIN
    image: nginx:1.17.7
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
    volumes:
      - ../distribution/frontend/:/usr/share/nginx/html/
      - ../conf/nginx.conf:/etc/nginx/conf.d/default.conf
    command: bash -c "nginx -g 'daemon off;'"
#    ports:
#      - ${NGINX_PORT}:80
    tty: true

#      - fabric_service
